### ISSUE TITLE
getContacts() returns 404 when 53 contact ids supplied

### ISSUE THREAD

**Issue by mbyrne00** [XeroAPI/xero-node#404] opened 2020-04-14 04:37 UTC
We are trying to call `xeroClient.accountingApi.getContacts()` for a single `tenantId` and an array of `ids`. When we supply `52` ids we get a response. When we supply `53` then there is a `404` with message `The resource you're looking for cannot be found`.

This seems like a strange, arbitrary number and maybe it's to do with payloads internally? The strange thing is that if we supply the same id 52 times it works (only returning one in array), but if we supply the same id 53 times it fails. The response is `404` and not `400` which makes me think this is an accidental side-effect rather than a request validation.

I originally posted this issue and mistakenly thought the client was not handling the response correctly, however further testing revealed what is happening. Realise it's not strictly a node client issue any more but any help would be greatly appreciated.

**Comment by SerKnight** [comment] 2020-04-14 20:04
Hi @mbyrne00  - this is an interesting one.. I will try and re-produce this week. First hunch is that you are right and its an issue with the payload return size.

**Comment by mbyrne00** [comment] 2020-04-15 02:19
Thanks @SerKnight - by the way I think the issue number is very fitting :)

**Comment by SerKnight** [comment] 2020-04-28 20:46
Hi all - I was able to reproduce this pretty easily ( 52 👍 -> 53 👎  )

I've got it queued to discuss with the API team. I will report back what I learn. Yea the workaround is just to limit those .where ID calls to max 52 records.. 

Closing since this is technically not an SDK issue.. But thank you for reporting & I will certainly report back with a reason why should I get one. It's an interesting find :)

**Closed by SerKnight** 2020-04-28 20:46 UTC

**Comment by mbyrne00** [comment] 2020-04-28 23:19
Thanks @SerKnight - when talking to them please note that it's not the _actual number of results returned_ that cause the error. As I mentioned earlier if you put the same id 53 times it gives the error. If you put the same id 52 times then it returns a single result successfully.

**Comment by SerKnight** [comment] 2020-04-29 00:17
Ha. So it turns out (pretty sure) this is actually caused by that extra uuid length passing the query string max length https://stackoverflow.com/questions/812925/what-is-the-maximum-possible-length-of-a-query-string Since this is a GET

I was having trouble getting proof as the encoded length was not showing exactly > 2048 but 95% sure that’s the reason. 

If you want to elaborate on your use case there might be a better way to filter on the api.
