### ISSUE TITLE
RPError: JWT not active yet, now 1579073794, nbf 1579073795

### ISSUE THREAD

**Issue by hanselke** [XeroAPI/xero-node#327] opened 2020-01-15 07:41 UTC
**SDK you're using (please complete the following information):**
 - Version 4.02

**Describe the bug**
When you try to authenticate, it fails after callback with error in title.

This is due to the system setting a nbf (not before) timestamp to accept the calling of 
 await xero.setAccessTokenFromRedirectUri(url);

**To Reproduce**
in xero-node-oauth2-app, just try to authenticate. it happens sometimes
**Expected behavior**
it should work all the time

**Screenshots**

**Additional context**
i've fixed it in my own app by adding a timeout before doing anything with the callback, but it seems like it's ALWAYS 1 ms lower then nbf whenever it causes an error. maybe make the nbf slightly earlier?

**Comment by SerKnight** [comment] 2020-01-22 19:56
Hey @hanselke - this should be fixed in `4.1.0` due to some refactors in the XeroClient.ts file, where the clock tolerance is setup: https://github.com/XeroAPI/xero-node/blob/master/src/xeroClient.ts#L40

If still dealing with this after updating - feel free to re-open if issue persists.

**Closed by SerKnight** 2020-01-22 19:56 UTC
Labels: 4.x, bug reported (?)

**Comment by varinderDeakin** [comment] 2020-02-24 01:32
Hey @SerKnight I am facing the same issue.

- Using SDK Version 4.1.7

I am running [https://github.com/XeroAPI/xero-node-oauth2-app](https://github.com/XeroAPI/xero-node-oauth2-app) while authenticating I am getting the below mentioned error

![image](https://user-images.githubusercontent.com/27680200/75124139-5f14bd80-5701-11ea-8a79-69d803ee24b5.png)

**Comment by devinrhode2** [comment] 2022-02-02 15:08
> Hey @hanselke - this should be fixed in 4.1.0 due to some refactors in the XeroClient.ts file, where the clock tolerance is setup: https://github.com/XeroAPI/xero-node/blob/master/src/xeroClient.ts#L40
Here's updated url: https://github.com/XeroAPI/xero-node/blob/4.1.0/src/xeroClient.ts#L40

**Comment by devinrhode2** [comment] 2022-02-02 15:48
Turns out, we had this issue with a different oauth implementation, but, it turned out, that the issue is because one developer's clock was off by 2.4 MINUTES (144 seconds). 

If you go to time.gov, here's what you don't want to see:
![CleanShot 2022-02-02 at 09 46 54](https://user-images.githubusercontent.com/539816/152187761-ebfd835f-5dfd-41fd-a4af-e6e9c89014ec.png)

Here's what you do want to see (very small offset):
![CleanShot 2022-02-02 at 09 47 02](https://user-images.githubusercontent.com/539816/152187790-121f505e-c1c9-453a-8f37-c3f78b6af78f.png)

As long as your servers have relatively accurate time, you shouldn't have this problem.
In theory you can increase clock tolerance to accommodate more inaccurate clocks.

**Comment by venus1344** [comment] 2022-10-11 23:51
hello @devinrhode2 

I'm just experiencing a similar issue while testing the oauth2-app. I don't quite understand the clock tolerance you're referring to on your solution above. May you shed more light on this? 

Thanks

**Comment by devinrhode2** [comment] 2022-10-12 03:50
I think ultimately you should just go to time.gov and try to tune your clock

**Comment by datluong255** [comment] 2023-01-09 01:48
I've come across the same situation and fixed it by 
![image](https://user-images.githubusercontent.com/110090141/211229938-cb09e908-2671-419c-887f-7c4302439b79.png)

**Comment by datluong255** [comment] 2023-01-09 01:52
I've come across the same situation and I just added clockTolerance > `Your clock is off by:` then it worked
![image](https://user-images.githubusercontent.com/110090141/211230019-4648c71d-8840-4f6f-9488-609293afc3b2.png)
![image](https://user-images.githubusercontent.com/110090141/211229992-2fa6ad38-9de1-4872-873b-ae828c3f8d16.png)
