### ISSUE TITLE
savePDF should reject if folder does not exists

### ISSUE THREAD

**Issue by ajouve** [XeroAPI/xero-node#250] opened 2019-01-27 14:19 UTC
Hi there,

I am using the method `xero.invoices.savePDF`, if the `savePath` does not exists I have `Error: ENOENT: no such file or directory, open` it should be return by a promise reject

**Comment by philals** [comment] 2019-01-27 19:01
Hi @ajouve Mind sending a PR for this?

**Comment by sapinder** [comment] 2019-02-08 05:42
Is there a way to get the pdf as arraybuffer? Actually my requirement is to provide a pdf to web client without saving this on my node server?

**Comment by ajouve** [comment] 2019-03-22 07:25
@sapinder 👍 Would be great

**Comment by iamam34** [comment] 2019-09-24 02:27
closing as duplicate of #261

**Closed by iamam34** 2019-09-24 02:27 UTC
