### ISSUE TITLE
error response Handling

### ISSUE THREAD

**Issue by monukanyal** [XeroAPI/xero-node#105] opened 2017-09-14 13:14 UTC
Hello,

when i am calling create contacts api with same data , i am getting response like:

{ Error: GET call failed with: 404
    at self.oa.get.stream (/Users/macmini/Documents/myds-node/node_modules/xero-node/lib/application.js:327:36)
    at passBackControl (/Users/macmini/Documents/myds-node/node_modules/xero-node/lib/oauth/oauth.js:406:25)
    at IncomingMessage.<anonymous> (/Users/macmini/Documents/myds-node/node_modules/xero-node/lib/oauth/oauth.js:422:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  data: { 'The resource you\'re looking for cannot be found': '' } }

I know, why it is coming but i don't want see any other information on terminal[mac] except data part['The resource you\'re looking for cannot be found']. please help me.

**Comment by philals** [comment] 2017-09-14 19:01
Hi @monukanyal Are you able to post the code that you are using? Also does https://app.xero.com/Application/History help? Are you able to use the other endpoints in the SDK?

**Comment by jordanwalsh23** [comment] 2017-09-14 22:37
This is a duplicate of Issue #21.

4xx errors are currently being treated as an error.  Whereas 404 should probably be treated as an empty response.

This is on the roadmap to resolve.

**Comment by jordanwalsh23** [comment] 2017-09-14 22:37
Closing as further updates will be tracked in #21

**Closed by jordanwalsh23** 2017-09-14 22:37 UTC
