### ISSUE TITLE
AuthenticationUnsuccessful error despite valid Bearer Token and Tenant ID

### ISSUE THREAD

**Issue by colophonemes** [XeroAPI/xero-node#432] opened 2020-07-08 16:51 UTC
**SDK you're using (please complete the following information):**
 - Version 4.7.3

**Describe the bug**

**To Reproduce**

- Create a new Demo Organisation
- Create a new App on Xero Developer MyApps
- Use XOAuth to get a tokenset for my Xero org (with scopes: `openid accounting.reports.read accounting.settings accounting.transactions accounting.contacts offline_access`)
- Create a `new XeroClient({ client_id, client_secret })` (referred to as `xero` below)
- Supply tokenset to the SDK via `xero.setTokenSet(tokenSetFromXOAuth)`
- Refresh the tokenset on init, using `xero.refreshWithRefreshToken(client_id, client_secret, tokenSetFromXOAuth.refresh_token)`
- Query active tenants, with `xero.updateTenants()`

All of this works fine, and each initialisation refreshes the token, and returns the authenticated tenants correctly. However, if I try to make a call to retrieve data from the API using the client, I receive the following error in the response body:

Example call:
```
const Invoices = await xero.accountingApi.getOrganisations(xero.tenants[0].id)
```

Response:
```
{"Type":null,"Title":"Forbidden","Status":403,"Detail":"AuthenticationUnsuccessful","Instance":"10fa664c-61e3-453e-b7f4-c087cfc82401","Extensions":{}}
```

Your [troubleshooting page](https://developer.xero.com/documentation/oauth2/troubleshooting) suggests that this could be either because of a missing "xero-tenant-id" header or a permissions issue.

Inspecting the error response object returned when I try to make a call, I can see that both the `xero-tenant-id` and `Authorization` headers are set correctly. Output of `console.log(err.response.request.headers)` as follows:

```
{
  'xero-tenant-id': '4aa445c5-c90b-439e-82a7-12faedfa3a4a',
  Authorization: 'Bearer eyJhbGciOiJSUz...tCZYO2pAaZpmHqQ',
  accept: 'application/json'
}
```

I've confirmed that the Bearer token matches the one on the client object (i.e. that stored at `xero.tokenSet.access_token`), and the Tenant ID comes from `xero.tenants[0].id`.

The same error occurs if I try a minimal CURL request:

```
curl -H 'xero-tenant-id: 4aa445c5-c90b-439e-82a7-12faedfa3a4a' -H 'Authorization: Bearer eyJhbGciOiJSUz...tCZYO2pAaZpmHqQ' https://api.xero.com/api.xro/2.0/Invoices
```

**Expected behavior**
The API call returns the requested objects

**Additional context**
I've tried this on both a new Demo Organization, and on one of our existing production orgs.

**Comment by SidneyAllen** [comment] 2020-07-08 17:12
@colophonemes - have you checked your scopes?

https://developer.xero.com/documentation/oauth2/scopes

If you are missing the right scope, after you add the relevant scope to your code, I recommend logging into Xero and navigate to settings > Connected Apps and disconnect your app to revoke the access token.  This will ensure when you go through the oauth flow again you'll get a fresh access token with the correct scopes.

**Comment by colophonemes** [comment] 2020-07-08 17:17
Do I have to specify the scopes in code, as well as in the XOAuth token request? The list of scopes as above (i.e. `openid accounting.reports.read accounting.settings accounting.transactions accounting.contacts offline_access`) is what I specified to XOAuth, and is also what appears on the client if I log out `xero.tokenSet.scope`.

**Comment by RettBehrens** [comment] 2020-07-08 17:18
@colophonemes the issue might be that you're using the 'Id' not the 'tenantId'

`{
        "id": "e1eede29-f875-4a5d-8470-17f6a29a88b1",
        "authEventId": "d99ecdfe-391d-43d2-b834-17636ba90e8d",
        "tenantId": "70784a63-d24b-46a9-a4db-0e70a274b056",
        "tenantType": "ORGANISATION",
        "tenantName": "Maple Florist",
        "createdDateUtc": "2019-07-09T23:40:30.1833130",
        "updatedDateUtc": "2020-05-15T01:35:13.8491980"
    }`

**Comment by colophonemes** [comment] 2020-07-08 17:22
@RettBehrens ah crap, that was it! 🤦 

Thank you, that's been extremely helpful.

I wonder if it might be worth noting this in the docs somewhere as a gotcha, as the fact that a tenant has both an `id` and a `tenantId` field is pretty confusing.

**Comment by RettBehrens** [comment] 2020-07-08 17:29
@colophonemes glad I could help and that it was an easy fix! Sorry it was confusing. We do have example calls, both the disconnect using the connection ID and a getInvoices call using the tenant ID in the xero-node sdk readme, however, I don't know off the top of my head if this is called out for example in the xoauth docs or oauth2 code flow docs - I'll look into it. Going to close this issue for now if you're all set, feel free to reopen if something comes up though.

**Closed by RettBehrens** 2020-07-08 17:29 UTC

**Comment by adamreisnz** [comment] 2021-03-10 09:10
Mmhh... everything in Xero is called `somethingID`, e.g. `contactID`, `tenantID`, `invoiceID`, so why is the connection ID not called `connectionID` for consistency?

**Comment by haydn** [comment] 2022-02-03 06:57
I just spent a lot of time on this problem today and I think that my main confusion was caused by the `xero.tenants` property and the `xero.updateTenants` method having misleading names. I feel like `xero.connections` and `xero.updateConnections` would be clearer and make it unlikely someone would mistake `xero.connections[0].id` for a tenant ID.
