### ISSUE TITLE
UnhandledPromiseRejectionWarning: AggregateError

### ISSUE THREAD

**Issue by Super-Chama** [XeroAPI/xero-node#390] opened 2020-03-24 07:00 UTC
**SDK Version**
 - Version 4.4.5

**Description**
I was testing out the Xero-node-oauth2 app since couple weeks back. It was functional at the beginning but since last week Xero authentication is interrupted with error `TimeoutError: Timeout awaiting 'request' for 2500ms` and following error is shown in terminal when server is started.

`(node:7393) UnhandledPromiseRejectionWarning: AggregateError: 
    TimeoutError: Timeout awaiting 'request' for 2500ms
        at ClientRequest.<anonymous> (/home/chamara/Development/xero-node-oauth2/node_modules/openid-client/node_modules/got/source/request-as-event-emitter.js:176:14)
        at ClientRequest.origin.emit (/home/chamara/Development/xero-node-oauth2/node_modules/@szmarczak/http-timer/source/index.js:37:11)
        at Immediate.timeoutHandler (/home/chamara/Development/xero-node-oauth2/node_modules/openid-client/node_modules/got/source/utils/timed-out.js:63:11)
    TimeoutError: Timeout awaiting 'request' for 2500ms
        at ClientRequest.<anonymous> (/home/chamara/Development/xero-node-oauth2/node_modules/openid-client/node_modules/got/source/request-as-event-emitter.js:176:14)
        at ClientRequest.origin.emit (/home/chamara/Development/xero-node-oauth2/node_modules/@szmarczak/http-timer/source/index.js:37:11)
        at Immediate.timeoutHandler (/home/chamara/Development/xero-node-oauth2/node_modules/openid-client/node_modules/got/source/utils/timed-out.js:63:11)
    at rejected (/home/chamara/Development/xero-node-oauth2/node_modules/p-some/index.js:71:11)
    at /home/chamara/Development/xero-node-oauth2/node_modules/p-some/index.js:85:5
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:7393) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7393) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code`

**To Reproduce**
1. Go to 'https://github.com/XeroAPI/xero-node-oauth2-app' and clone project
2. Run Project

**Screenshots**
![image](https://user-images.githubusercontent.com/12880059/77397172-19fcad80-6dcb-11ea-89c9-4f90964d3ad8.png)

**Comment by SerKnight** [comment] 2020-03-24 17:02
Hey @Super-Chama - does this happen for you every time?

Assuming you ran `npm install` prior to `npm run start-dev`

**Comment by Super-Chama** [comment] 2020-03-24 17:35
Hey @SerKnight thanks for following up. Yeah I ran `npm install` to completion and without errors. And Yes this keeps happening 2/3 times. When it works, it works without an issue.

**Comment by Super-Chama** [comment] 2020-03-24 17:40
I must also add that this works without fault on my work pc which is running Mint 16 with Node 12. Since the outbreak I'm working on my laptop 
at home which is running a fresh install of Mint 18 and node 12 where this issue is happening. To verify this isn't a OS firewall issue I've disabled ufw and tried but no luck. Also I've followed up on a similar issue with openaid-client [where](https://github.com/panva/node-openid-client/issues/172)  they've suggested to increased http timeout and did that. But still it'll occasionally get timeouts.

**Comment by SerKnight** [comment] 2020-03-27 20:29
Hey @Super-Chama  - so without a way to reproduce its hard to plan/issue a type of fix. 

I will close this issue for now - but if you can get a simple repo setup or find the dependency / line of code please re-open and we can go from there.

You said you implemented panva's idea in that thread of https://github.com/panva/node-openid-client/tree/master/docs#customizing-http-requests ?

**Closed by SerKnight** 2020-03-27 20:29 UTC

**Comment by Super-Chama** [comment] 2020-03-30 03:08
Hey @SerKnight , I understand that. I'm surprised that no one else is getting this issue but me. makes me suspicious about something wrong in my setup. 

Yes as per suggestion in _node-openid-client_ repo i've edidted XeroClient.js to include following as a temp fix.

```
const { custom } = require("openid-client");

custom.setHttpOptionsDefaults({
    timeout: 5000,
});
```

Which does increase the timeout value, but still occasionally get that timeout error. I'm not confident that this is a fix tho. It's just delaying the inevitable.

**Comment by DevJHansen** [comment] 2020-04-10 08:39
@Super-Chama  I'm also getting this issue. Usually things work perfectly for a couple days then all of a sudden it won't work anymore. 
If I keep refreshing the page or give it some time it will start to work again. 

Has increasing the timeout been successful in solving this problem?

**Comment by Super-Chama** [comment] 2020-04-24 10:57
@DevJHansen Hey, thats a bummer. Increasing the timeout just reduces the chance of this happening but it happens then and now. maybe @SerKnight can help you out

**Comment by Super-Chama** [comment] 2020-06-09 19:16
@SerKnight  Recently I've updated to xero-node 4.60. but this issue still keeps happening to me. I've logged the outgoing http/s requests using a logger in node. Kindly see if it can give you a hint to what causes this problem.

2020-06-10T00:20:06:   error: Error: socket hang up
2020-06-10T00:20:06:       at connResetException (internal/errors.js:609:14)
2020-06-10T00:20:06:       at TLSSocket.socketCloseListener (_http_client.js:400:25)
2020-06-10T00:20:06:       at TLSSocket.emit (events.js:327:22)
2020-06-10T00:20:06:       at TLSSocket.EventEmitter.emit (domain.js:482:12)
2020-06-10T00:20:06:       at net.js:674:12
2020-06-10T00:20:06:       at TCP.done (_tls_wrap.js:566:7) {
2020-06-10T00:20:06:     code: 'ECONNRESET'
2020-06-10T00:20:06:   }

See the full log [in this pastebin](https://pastebin.com/hsXSEE5F)

**Comment by clethrill** [comment] 2020-08-26 05:27
I've started experiencing this issue from today, never had it before, changed nothing in my codebase. I get it attempting to exchange a code for access tokens through the node-sdk. 

Like @Super-Chama said I did get it to go through a couple of times, seems to be randomly failing.

My error message:

`TimeoutError: Timeout awaiting 'request' for 2500ms
 at ClientRequest.<anonymous> (/var/task/node_modules/got/source/request-as-event-emitter.js:176:14)
 at Object.onceWrapper (events.js:422:26)
 at ClientRequest.emit (events.js:327:22)
 at ClientRequest.EventEmitter.emit (domain.js:482:12)
 at ClientRequest.origin.emit (/var/task/node_modules/@szmarczak/http-timer/source/index.js:37:11)
 at Immediate.timeoutHandler (/var/task/node_modules/got/source/utils/timed-out.js:63:11)
 at processImmediate (internal/timers.js:458:21)
 at process.topLevelDomainCallback (domain.js:137:15)`

**Comment by sandorvasas** [comment] 2020-08-31 21:33
Just got a ton of timeout errors. Token renewals failed, client accounts (10+) are disconnected. Openid timeout was set to 10,000ms. What is going on with Xero API? What are these lags?

**Comment by BlueTwistnz** [comment] 2020-08-31 21:41
@clethrill We also started getting timeout issues on the 26th (same day you did). Nothing changed in our codebase or servers. Like you randomly failing. 

Logs from Xero's end showed us handing in a token and being issued a new token, but we never received the new token due to timeout.

**Comment by brucem1976** [comment] 2020-09-17 11:50
Also experience this issue intermittently - it seems to be dependent on current network speed and reliability - we process 10,000's of Invoices via webhooks and then a spate of these appear, and then they disappear on their own, and come back later
