### ISSUE TITLE
[v4] refreshToken() fails after a ValidationException error occurs on createContact() API call.

### ISSUE THREAD

**Issue by dillonparfitt** [XeroAPI/xero-node#299] opened 2019-11-26 12:03 UTC
**SDK you're using (please complete the following information):**
 - Version 4.0.2

**Describe the bug**
The refreshToken() call fails with "invalid_grant" after a "ValidationException" error occurs on any of the API calls. I have tested calling refreshToken() after successful api calls and it works correctly, but it fails after attempting to create a contact with a contactNumber that already exists. This forces the user to reconnect their Xero account. 

**To Reproduce**
1. Create a new XeroClient with the following scopes: openid, email, profile, offline_access, accounting.transactions, accounting.contacts
2. Connect to xero account with the OAuth 2 flow and save tokens
3. Create a contact with xero.accountingApi.createContact() with a contactNumber that has already been created on Xero.  (Will throw an error)
4. Attempt to refresh the token with refreshToken(). This throws an "invalid_grant" error.

**Expected behavior**
It is expected to be able to refresh the token after a "ValidationException" error occurs. 

**Screenshots**
NA

**Additional context**
On every refresh all the new tokens are stored and used for subsequent api calls.

**Comment by SidneyAllen** [comment] 2019-12-05 15:05
@dillonparfitt - thanks for the feedback and clearly documenting how to reproduce.

Team will be out next week for an offsite, but will prioritize looking at this the week of Dec 16th.

**Comment by tglennan** [comment] 2020-01-02 03:43
I'm facing the same issue on createInvoice() API calls. That is, refreshToken() throws an "invalid_grant" error after a ValidationException on createInvoice().

Has there been any progress on this issue?

**Comment by SerKnight** [comment] 2020-01-22 01:19
hey @tglennan  - @dillonparfitt 

I've tried my best to recreate the issue & recorded a short video.

https://drive.google.com/open?id=19VfjsCIKLda6sWM6hwZyatTFTkp0RU1V&authuser=0

This is clearly an issue as a few folks have reported.. Just trying to narrow in on the steps to reproduce it so I can get a valid fix out there asap. Let me know if you can document steps to reproduce a bit more clearly.

Also if anyone has a case logged with our api@xero.com team - I can reach out to get the details of your organisation and can lookup more specific logs.

I've also got a very basic sample app you could try to fork and reproduce in: https://github.com/SerKnight/xero-node-basic-app if thats easier for you.

Ref #307  as this is a duplicate..

**Comment by philliplakis** [comment] 2020-02-02 23:00
@SerKnight sure its fixed now, thanks 🙏 . 

But this issue can be replicated with `v4.0.2`!

**Comment by SerKnight** [comment] 2020-02-04 17:17
Closing for now, please re-surface if it comes back up.

**Closed by SerKnight** 2020-02-04 17:17 UTC
Labels: 4.x, bug reported (?)

**Comment by daffron** [comment] 2020-02-07 06:06
I seem to be having this issue now (v4.1.5) , anything else that could cause this?

**Comment by Roncy13** [comment] 2020-03-06 02:50
me too im having

**Comment by SerKnight** [comment] 2020-03-09 23:41
Hey all -- this looks like its happening in a previously released version of the package. I would love to help but I'm unable to re-recreate. Here is a very simple repo using the xero-node 4.4.3 
> https://github.com/XeroAPI/xero-node-oauth2-app

If we can get this re-created systematically I can more effectively deploy a fix.

**Comment by aprilmintacpineda** [comment] 2022-12-12 07:50
For those who will encounter this, this also happens when you forget to call `await xero.initialize()` and then called `xero.refreshToken`, it results to the following error:

```
TypeError: Cannot read property 'refresh' of undefined
    at XeroClient.<anonymous> (node_modules/xero-node/dist/XeroClient.js:131:63)
```

which points to

```ts
const refreshedTokenSet = yield this.openIdClient.refresh(this._tokenSet.refresh_token);
```

`this.openIdClient` will be undefined because it's only defined in the `initialize` method which is on `node_modules/xero-node/dist/XeroClient.js:69`

```ts
this.openIdClient = new issuer.Client({
    client_id: this.config.clientId,
    client_secret: this.config.clientSecret,
    redirect_uris: this.config.redirectUris,
});
```
