### ISSUE TITLE
Retry failed requests to retrieve new refresh token

### ISSUE THREAD

**Issue by zxxc** [XeroAPI/xero-node#455] opened 2020-09-08 04:35 UTC
**SDK you're using (please complete the following information):**
 - Version ^4.7.5

**Is your feature request related to a problem? Please describe.**
If we cannot refresh the Refresh token we are removing user credentials from our db and ask the user to re-enable his integration manually.

Issue:
Whenever we experience timeout or connectivity issue when we are trying to obtain a refresh token, for example,
we are disabling integration with Xero

**Describe the solution you'd like**
I think would be good if the Xero library can retry failed requests automatically. But allow us to update configuration values by default, for example, to decrease timeout or increase the number of retries.

**Describe alternatives you've considered**
As a workaround, we are retrying requests to Xero in our own code
But I think this is useful for other clients as well.
And you guys know better cases whenever request can be retried and which retry policy suits your API better

**Additional context**
Just a note, our solution is also doesn't look good, as we cannot use instanceOf when we are getting an error from your library
For example, if we do not want to retry we have to cast error to any (we use ts) and do something like this:
```
if ((error as any).error === 'invalid_grant') {
        throw new pRetry.AbortError(new RefreshTokenError('refresh token is invalid'));
      }
```

**Comment by SerKnight** [comment] 2020-09-08 18:49
Hi @zxxc - 

Last week the project was updated to support the configuration of the timeout time: https://github.com/XeroAPI/xero-node/releases/tag/4.8.1

```javascript
const xero = new XeroClient({
  clientId: 'YOUR_CLIENT_ID',
  clientSecret: 'YOUR_CLIENT_SECRET',
  redirectUris: [`http://localhost:${port}/callback`],
  scopes: 'openid profile email accounting.transactions offline_access'.split(" "),
  state: 'returnPage=my-sweet-dashboard', // custom params (optional)
  httpTimeout: 3000 // ms (optional)
});
```

As for retrying of failed requests automatically.. I'd be keen on hearing more thoughts about this. It is something that has come up in the past as a feature for this project, however I fear it just assumes too much about the structure of each project.

From what I understand there would need to be some kind of persistence to process the retry's - or else we might fall into a trap of looping or just failing a request (n) times based on some configuration.

How would you imagine the queue (or state) of failed requests be persisted?

**Comment by SerKnight** [comment] 2020-09-08 18:50
If you can share additional surrounding code on how you currently handle `invalid_grant` failures it might get the ball rolling.

**Comment by zxxc** [comment] 2020-09-09 00:03
```
import * as pRetry from 'p-retry';
import { XeroClient } from 'xero-node';

export class RefreshTokenError extends Error {}

async function refreshXeroTokenWithRetry(client: XeroClient) {
  return pRetry(async () => client.refreshToken(), {
    retries: 5,
    factor: 1,
    minTimeout: 500,
    onFailedAttempt: error => {
      logger.warning('failed refreshing token', error);

      /**
       * If refresh token is invalid -> No need to retry
       * We are getting this error from Xero SDK. SDK does not specific error type for this.
       */
      if ((error as any).error === 'invalid_grant') {
        throw new pRetry.AbortError(new RefreshTokenError('refresh token is invalid'));
      }
    },
  });
}```
Do you see any issue with this simple solution?
Could you elaborate on scenarios that you think may lead to requests queue?

**Comment by SerKnight** [comment] 2020-09-09 18:13
Ah interesting so you just wrap in a library with some retry config.. Have you figured out what the `invalid_grant` was caused by? That might be the bigger question here. Maybe better to just fail once instead of loop and fail 5 times. Do you find that hitting same request again is going through subsequent times?

**Comment by zxxc** [comment] 2020-09-14 23:28
I think we don't need a bug label here.
Line: `throw new pRetry.AbortError(new RefreshTokenError('refresh token is invalid'));` stops retries

So what code above is doing:
It tries to update refresh token 5 times if any error happen, but stop retrying if invalid_grant received

**Comment by SerKnight** [comment] 2020-09-29 17:40
Hi @zxxc - going to close this one out. I don't think adding another dependency for retry functionality is the right step at this time given what we know.

If you can capture additional logging surrounding why the `invalid_grant` is happening we can open a case with API tech support and dig into logs and try to figure out the root causes.

**Closed by SerKnight** 2020-09-29 17:40 UTC
Labels: Status: In Discussion, Version: 4.x
