### ISSUE TITLE
Problem with creating Credit notes

### ISSUE THREAD

**Issue by sksankarraj** [XeroAPI/xero-node#551] opened 2021-09-22 04:12 UTC
Hello team,

We have been using Xero for long time and we were consuming xero-apis in a traditional way using `node-fetch`.

We are trying to move our API calls to Xero-Node wrappers. But we are facing **serialization** issues in all services, invoices, credit notes etc.

Example - credit note:
<details>
<summary>Code we are using:</summary>
<p>

```js
const createXeroCreditNote = async (invoiceID) => {
  const tokenSet = await getTokenSet();
  await xero.setTokenSet(tokenSet.token_set);
  const unitdp = 4;

  let invoice;
  try {
    const response = await xero.accountingApi.getInvoice(tokenSet.tenant_id, invoiceID, unitdp);
    invoice = response.body.invoices[0];
  } catch (err) {
    const error = JSON.stringify(err.response.body, null, 2);
    throw new ErrorHandler(500, `Getting invoice to void error: ${err} => ${error}`);
  }

  logger.info(`Creating credit note for invoice of ${invoice.reference}`);
  const contact = {
    contactID: invoice.contact.contactID,
  };

  const lineItems = invoice.lineItems.map(lineItem => ({
    description: lineItem.description,
    quantity: lineItem.quantity,
    unitAmount: lineItem.unitAmount,
    accountCode: lineItem.accountCode,
    itemCode: lineItem.itemCode,
  }));

  const creditNotes = {
    creditNotes: [{
      type: CreditNote.TypeEnum.ACCRECCREDIT,
      contact: contact,
      date: moment(),
      lineItems,
    }]
  };

  try {
    const response = await xero.accountingApi.createCreditNotes(tokenSet.tenant_id, creditNotes, true, unitdp);
    logger.info('Credit note successfully created - %o', response.body || response.response.statusCode);
    return response.body.creditNotes[0];
  } catch (err) {
    const error = JSON.stringify(err, null, 2);
    console.log(error);
    throw new ErrorHandler(500, `createXeroCreditNote error: ${err} => ${error}`);
  }
};
```

</p>
</details>  

<details>
<summary>Error I get</summary>
<p>

```json
{
  "response": {
    "statusCode": 400,
    "body": {
      "ErrorNumber": 10,
      "Type": "ValidationException",
      "Message": "A validation exception occurred",
      "Elements": [
        {
          "CreditNoteID": "00000000-0000-0000-0000-000000000000",
          "ID": "00000000-0000-0000-0000-000000000000",
          "HasErrors": true,
          "Type": "ACCRECCREDIT",
          "Contact": {
            "ContactID": "54b2e385-9987-490f-b901-a47b6fd0f501",
            "Addresses": [],
            "Phones": [],
            "ContactGroups": [],
            "ContactPersons": [],
            "HasValidationErrors": false,
            "ValidationErrors": []
          },
          "DateString": "2021-09-22T03:02:24",
          "Date": "/Date(1632279744252)/",
          "Status": "DRAFT",
          "LineAmountTypes": "Exclusive",
          "LineItems": [
            {
              "ItemCode": "C01-C020003-030-1",
              "Description": "Circle CBD 20 Oil - 30ml",
              "UnitAmount": 119,
              "TaxType": "BASEXCLUDED",
              "TaxAmount": 0,
              "LineAmount": 238,
              "AccountCode": "200",
              "Tracking": [],
              "Quantity": 2,
              "AccountID": "acafc55b-57e9-4d19-b9a6-66d30d4b50b7",
              "ValidationErrors": []
            },
            {
              "ItemCode": "DIS-FEE",
              "Description": "Pharmacy Dispensing Fee",
              "UnitAmount": 35,
              "TaxType": "BASEXCLUDED",
              "TaxAmount": 0,
              "LineAmount": 35,
              "AccountCode": "200",
              "Tracking": [],
              "Quantity": 1,
              "AccountID": "acafc55b-57e9-4d19-b9a6-66d30d4b50b7",
              "ValidationErrors": []
            },
            {
              "Tracking": [],
              "ValidationErrors": []
            },
            {
              "Tracking": [],
              "ValidationErrors": []
            }
          ],
          "SubTotal": 273,
          "TotalTax": 0,
          "Total": 273,
          "CurrencyCode": "AUD",
          "ValidationErrors": [
            {
              "Message": "The description field is mandatory for each line item."
            },
            {
              "Message": "The description field is mandatory for each line item."
            }
          ]
        },
        {
          "CreditNoteID": "00000000-0000-0000-0000-000000000000",
          "ID": "00000000-0000-0000-0000-000000000000",
          "HasErrors": true,
          "DateString": "2021-09-22T00:00:00",
          "Date": "/Date(1632268800000+0000)/",
          "Status": "DRAFT",
          "LineAmountTypes": "Exclusive",
          "LineItems": [],
          "SubTotal": 0,
          "TotalTax": 0,
          "Total": 0,
          "CurrencyCode": "AUD",
          "ValidationErrors": [
            {
              "Message": "One or more line items must be specified"
            },
            {
              "Message": "Type is required."
            },
            {
              "Message": "A Contact must be specified for this type of transaction"
            }
          ]
        }
      ]
    },
    "headers": {
      "content-type": "application/json; charset=utf-8",
      "content-length": "2898",
      "server": "nginx",
      "xero-correlation-id": "6b7a5ebe-2690-4a1b-89fc-a1827c3ebfa4",
      "x-appminlimit-remaining": "9996",
      "x-minlimit-remaining": "57",
      "x-daylimit-remaining": "4796",
      "expires": "Wed, 22 Sep 2021 03:02:24 GMT",
      "cache-control": "max-age=0, no-cache, no-store",
      "pragma": "no-cache",
      "date": "Wed, 22 Sep 2021 03:02:24 GMT",
      "connection": "close",
      "x-client-tls-ver": "tls1.3"
    },
    "request": {
      "uri": {
        "protocol": "https:",
        "slashes": true,
        "auth": null,
        "host": "api.xero.com",
        "port": null,
        "hostname": "api.xero.com",
        "hash": null,
        "search": "?summarizeErrors=true&unitdp=4",
        "query": "summarizeErrors=true&unitdp=4",
        "pathname": "/api.xro/2.0/CreditNotes",
        "path": "/api.xro/2.0/CreditNotes?summarizeErrors=true&unitdp=4",
        "href": "https://api.xero.com/api.xro/2.0/CreditNotes?summarizeErrors=true&unitdp=4"
      },
      "method": "PUT",
      "headers": {
        "user-agent": "xero-node-4.15.0",
        "xero-tenant-id": "9033f7ba-e92f-4510-bbda-01d4dfa299e9",
        "Authorization": "Bearer  ",
        "accept": "application/json",
        "content-type": "application/json",
        "content-length": 397
      }
    }
  },
  "body": {}
}
```
</p>
</details>  

Please check the response I have posted in error.

There are **SERIALIZATION** issues 2 here.

1. You can there are 2 credit notes in the response, but in the code you can see I have added only one CN and there is no way it can be 2 CN from code. I don't how it became 2 in the response.

2. You can see the validation error from first credit note which is the one I'm passing to xero. it says `"Message": "The description field is mandatory for each line item."`. Even in the response data that xero returns has the description value. How it is possible to produce this error idk.

Please help me with these issues I'm stuck here.

**Comment by dev-welli** [comment] 2021-09-22 08:20
@sksankarraj Can you contact Xero API Support at api@xero.com with the details of your integration:
- ClientID of your app
- Timestamps (and timezone) of the calls that generated the error

We can then check the application's logs to investigate.

As I think this is not an SDK issue, I'll close this issue for now.

**Closed by dev-welli** 2021-09-22 08:20 UTC

**Comment by sksankarraj** [comment] 2021-09-22 11:19
AFAIK, This is not an App issue, As I explained in the problem, I can use any http libraries to create Credit notes, invoices etc. I'm using the same data, same xero account but with Xero-Node wrapper, where I'm having this issue.

I don't think This issue can be closed.

**Comment by sksankarraj** [comment] 2021-09-22 14:29
NVM, i'm going back to using traditional http call.

**Comment by MattBidewell** [comment] 2021-09-23 12:57
I think this needs to be opened.

The internal serialize function is creating an additional entry where all values are undefined for what appears to be all use cases including creating invoices.

Here is an example: 

The invoice I'm creating...

![image](https://user-images.githubusercontent.com/8826525/134510201-7ba51ffe-83cb-4f7f-a337-f4db42a99ebc.png)

As you can see the invoice is one, with one line item.

Inside the accountApi.js the code serializes the invoices and sets it as the body of localVarRequestOptions.

![image](https://user-images.githubusercontent.com/8826525/134510472-327f93b7-ed5a-470a-aaf6-e14047fa8940.png)


As you can see the Array of invoices has an additional invoice, there is also an additional line item where all variables are undefined.

Unfortunately, this has made using this entire package unusable.

Could this be investigated?

**Comment by sksankarraj** [comment] 2021-09-24 03:10
Oh thanks god @MattBidewell, I thought I was alone. 

This is exactly what I'm facing.

This is exactly how I debugged.

**Comment by sksankarraj** [comment] 2021-09-24 03:13
Another Issue I have raised a while ago!. - https://github.com/XeroAPI/xero-node/issues/508#issue-836989908

**Comment by MattBidewell** [comment] 2021-09-24 09:24
I think the problem is, the code is auto-generated based on OpenAPI specs. But I would have expected it to get picked up or at least checked before it went into production. As far as I'm aware, any feature that serializes or deserializes a message would result in an additional undefined. 

I'm going to see if I can hack a fork of it temporarily and use that for the time being. 

Would be good to get @dev-welli opinion on the problemo!

**Comment by RettBehrens** [comment] 2021-09-24 18:51
I am unable to replicate the issue using Xero-Node v4.15.0. 

With each release that adds new methods we add those methods to our kitchen sink sample app and test those calls to verify functionality.
https://github.com/XeroAPI/xero-node-oauth2-app

In the past 30 days Xero-Node users have made:
POST: 4,963,388 API calls
PUT: 2,159,183 API calls

I've tested using two of our sample apps:

Node and Express without TypeScript
https://github.com/XeroAPI/xero-node-serializer-test

Node and Express with TypeScript
https://github.com/XeroAPI/xero-node-oauth2-ts-starter

```
serializer call:  {
  Invoices: [
    {
      Type: 'ACCREC',
      Contact: [Object],
      LineItems: [Array],
      Date: '2021-09-24',
      DueDate: '2021-09-25',
      LineAmountTypes: undefined,
      InvoiceNumber: undefined,
      Reference: undefined,
      BrandingThemeID: undefined,
      Url: undefined,
      CurrencyCode: undefined,
      CurrencyRate: undefined,
      Status: undefined,
      SentToContact: undefined,
      ExpectedPaymentDate: undefined,
      PlannedPaymentDate: undefined,
      CISDeduction: undefined,
      CISRate: undefined,
      SubTotal: undefined,
      TotalTax: undefined,
      Total: undefined,
      TotalDiscount: undefined,
      InvoiceID: undefined,
      RepeatingInvoiceID: undefined,
      HasAttachments: undefined,
      IsDiscounted: undefined,
      Payments: undefined,
      Prepayments: undefined,
      Overpayments: undefined,
      AmountDue: undefined,
      AmountPaid: undefined,
      FullyPaidOnDate: undefined,
      AmountCredited: undefined,
      UpdatedDateUTC: undefined,
      CreditNotes: undefined,
      Attachments: undefined,
      HasErrors: undefined,
      StatusAttributeString: undefined,
      ValidationErrors: undefined,
      Warnings: undefined
    }
  ]
}
localVarRequestOptions:  {
  method: 'PUT',
  qs: {},
  headers: {
    'user-agent': 'xero-node-4.15.0',
    'xero-tenant-id': '07f32319-daaf-4548-b589-d6f06f7b407f'
  },
  uri: 'https://api.xero.com/api.xro/2.0/Invoices',
  useQuerystring: false,
  json: true,
  body: { Invoices: [ [Object] ] }
}
invoices:  [
  Invoice {
    type: 'ACCREC',
    contact: Contact {
      contactID: 'adf801de-a142-4670-906f-0d46c5d7c693',
      contactNumber: undefined,
      accountNumber: undefined,
      contactStatus: 'ACTIVE',
      name: 'Gable Print',
      firstName: undefined,
      lastName: undefined,
      emailAddress: '',
      skypeUserName: undefined,
      contactPersons: [],
      bankAccountDetails: '',
      taxNumber: undefined,
      accountsReceivableTaxType: undefined,
      accountsPayableTaxType: undefined,
      addresses: [Array],
      phones: [Array],
      isSupplier: false,
      isCustomer: true,
      defaultCurrency: undefined,
      xeroNetworkKey: undefined,
      salesDefaultAccountCode: undefined,
      purchasesDefaultAccountCode: undefined,
      salesTrackingCategories: [],
      purchasesTrackingCategories: [],
      trackingCategoryName: undefined,
      trackingCategoryOption: undefined,
      paymentTerms: undefined,
      updatedDateUTC: 2021-09-13T18:03:42.080Z,
      contactGroups: [],
      website: undefined,
      brandingTheme: undefined,
      batchPayments: undefined,
      discount: undefined,
      balances: undefined,
      attachments: undefined,
      hasAttachments: undefined,
      validationErrors: undefined,
      hasValidationErrors: false,
      statusAttributeString: undefined
    },
    lineItems: [ [LineItem] ],
    date: 2021-09-24T00:00:00.000Z,
    dueDate: 2021-09-25T00:00:00.000Z,
    lineAmountTypes: 'Exclusive',
    invoiceNumber: 'INV-0055',
    reference: '',
    brandingThemeID: '5d4dd402-c851-497e-aae1-9ff265c0d15a',
    url: undefined,
    currencyCode: 'GBP',
    currencyRate: 1,
    status: 'DRAFT',
    sentToContact: false,
    expectedPaymentDate: undefined,
    plannedPaymentDate: undefined,
    cISDeduction: undefined,
    cISRate: undefined,
    subTotal: 10,
    totalTax: 0,
    total: 10,
    totalDiscount: undefined,
    invoiceID: 'a6a5f183-850a-4e65-84f1-819bc040be6d',
    repeatingInvoiceID: undefined,
    hasAttachments: undefined,
    isDiscounted: false,
    payments: undefined,
    prepayments: [],
    overpayments: [],
    amountDue: 10,
    amountPaid: 0,
    fullyPaidOnDate: undefined,
    amountCredited: undefined,
    updatedDateUTC: 2021-09-24T17:53:08.470Z,
    creditNotes: undefined,
    attachments: undefined,
    hasErrors: false,
    statusAttributeString: undefined,
    validationErrors: undefined,
    warnings: undefined
  }
]
serializer call:  {
  Contacts: [
    {
      ContactID: undefined,
      ContactNumber: undefined,
      AccountNumber: undefined,
      ContactStatus: undefined,
      Name: 'Bruce Banner',
      FirstName: undefined,
      LastName: undefined,
      EmailAddress: 'hulk@avengers.com',
      SkypeUserName: undefined,
      ContactPersons: undefined,
      BankAccountDetails: undefined,
      TaxNumber: undefined,
      AccountsReceivableTaxType: undefined,
      AccountsPayableTaxType: undefined,
      Addresses: undefined,
      Phones: [Array],
      IsSupplier: undefined,
      IsCustomer: undefined,
      DefaultCurrency: undefined,
      XeroNetworkKey: undefined,
      SalesDefaultAccountCode: undefined,
      PurchasesDefaultAccountCode: undefined,
      SalesTrackingCategories: undefined,
      PurchasesTrackingCategories: undefined,
      TrackingCategoryName: undefined,
      TrackingCategoryOption: undefined,
      PaymentTerms: undefined,
      UpdatedDateUTC: undefined,
      ContactGroups: undefined,
      Website: undefined,
      BrandingTheme: undefined,
      BatchPayments: undefined,
      Discount: undefined,
      Balances: undefined,
      Attachments: undefined,
      HasAttachments: undefined,
      ValidationErrors: undefined,
      HasValidationErrors: undefined,
      StatusAttributeString: undefined
    }
  ]
}
localVarRequestOptions:  {
  method: 'PUT',
  qs: {},
  headers: {
    'user-agent': 'xero-node-4.15.0',
    'xero-tenant-id': '07f32319-daaf-4548-b589-d6f06f7b407f'
  },
  uri: 'https://api.xero.com/api.xro/2.0/Contacts',
  useQuerystring: false,
  json: true,
  body: { Contacts: [ [Object] ] }
}
contacts:  [
  Contact {
    contactID: '4e0ad2b8-f80c-42e6-bd1f-0a910b342317',
    contactNumber: undefined,
    accountNumber: undefined,
    contactStatus: 'ACTIVE',
    name: 'Bruce Banner',
    firstName: undefined,
    lastName: undefined,
    emailAddress: 'hulk@avengers.com',
    skypeUserName: undefined,
    contactPersons: [],
    bankAccountDetails: '',
    taxNumber: undefined,
    accountsReceivableTaxType: undefined,
    accountsPayableTaxType: undefined,
    addresses: [ [Address], [Address] ],
    phones: [ [Phone], [Phone], [Phone], [Phone] ],
    isSupplier: false,
    isCustomer: false,
    defaultCurrency: undefined,
    xeroNetworkKey: undefined,
    salesDefaultAccountCode: undefined,
    purchasesDefaultAccountCode: undefined,
    salesTrackingCategories: [],
    purchasesTrackingCategories: [],
    trackingCategoryName: undefined,
    trackingCategoryOption: undefined,
    paymentTerms: undefined,
    updatedDateUTC: 2021-09-24T17:54:19.280Z,
    contactGroups: [],
    website: undefined,
    brandingTheme: undefined,
    batchPayments: undefined,
    discount: undefined,
    balances: undefined,
    attachments: undefined,
    hasAttachments: undefined,
    validationErrors: undefined,
    hasValidationErrors: false,
    statusAttributeString: undefined
  }
]
```

I understand your frustration and I'm keen to help get you unstuck. If you could, please try to replicate your issue using one of the two above sample repos and submit a PR to the repo

**Comment by IlyaShkurenko** [comment] 2023-02-02 06:49
I have same issue on 14.32.0. This making this package not usable

**Comment by MattBidewell** [comment] 2023-02-02 10:09
@IlyaShkurenko Hey,

Its been a while but I believe this was happening to me because we had an additional package in our NodeJS project that was modifying the original Array prototype. I cant remember off the top of my head which project it was but it generated a clash with xero-node package and resulted in the strange behaviour.

**Comment by fishsaidno** [comment] 2023-12-21 08:16
Identical issues here. No problem with regular HTTP requests.

Time is simply not available to debug this packages serialisation process within our specific environment.

It'd be nice if we could have an option to skip whatever serialisation this package insists on performing and just provide our own JSON string for the request body.

**Comment by sksankarraj** [comment] 2023-12-23 18:09
As @MattBidewell said, you might have some package that is updating the array.prototype globally, which is being used by ObjectSerialiser causing these issues.
